apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-tcp-app4
  namespace: app4
spec:
  type: NodePort 
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30353 
    protocol: TCP
    name: dashboard
  - port: 8090
    targetPort: 8090
    nodePort: 30355 
    protocol: TCP
    name: google-dns-tcp
  selector:
    app: app4-nginx-ingress
