apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-tcp-app5
  namespace: app5
spec:
  type: NodePort 
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30454
    protocol: TCP
    name: dashboard
  - port: 8091
    targetPort: 8091
    nodePort: 30455
    protocol: TCP
    name: nginx-org-tcp-snippet
  selector:
    app: app5-nginx-ingress
