apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-tcp-app3
  namespace: app3
spec:
  type: NodePort 
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30254 
    protocol: TCP
    name: dashboard
  - port: 5353
    targetPort: 5353
    nodePort: 30255 
    protocol: TCP
    name: dns-tcp
  selector:
    app: app3-nginx-ingress
